name: Generate 3D Contribution Map

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D contribution graph
    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 10
          SETTING_JSON: .github/3d-contrib-settings.json

      - name: Commit and push 3D contribution graph
        run: |
          git config --global user.name "Nithish-o7"
          git config --global user.email "nithisshhpersonal@gmail.com"
          git add -A
          git commit -m "chore: update 3D contribution graph" || echo "Nothing to commit"
          git push
